language: python
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- pypy
- pypy3
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- travis_retry pip install .
- travis_retry pip install coveralls
- travis_retry pip install coverage
script:
  PYTHONPATH=. coverage run -m nose2.__main__ -v
after_success:
- coveralls
deploy:
  provider: pypi
  user: the_drow
  password:
    secure: UprHllwkY0QzmO5mGl30LpJcpdnyf9wRkrXjifeEuOFjBAosWISa0vOPd6OMv8oZ5zWlEODiMRPVxHvBsjqo2nKLxSRh98Vc6vZCZBNc1GZEcbkAQDntQCnUwQhwWlrE8imcgjHAWlOvFUzzhrCF6l97TLFe7hRJl/Ms4LLJ1QI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: nose-devs/nose2
matrix:
  fast_finish: true
